// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PremiumCalculator.Web.API.Data;

namespace PremiumCalculator.Web.API.Migrations
{
    [DbContext(typeof(PremiumCalculatorWebAPIContext))]
    partial class PremiumCalculatorWebAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PremiumCalculator.Web.API.Models.Occupation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<int>("OccupationTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Occupation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cleaner",
                            OccupationTypeId = 3
                        },
                        new
                        {
                            Id = 2,
                            Name = "Doctor",
                            OccupationTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Author",
                            OccupationTypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Farmer",
                            OccupationTypeId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mechanic",
                            OccupationTypeId = 4
                        },
                        new
                        {
                            Id = 6,
                            Name = "Forist",
                            OccupationTypeId = 3
                        });
                });

            modelBuilder.Entity("PremiumCalculator.Web.API.Models.OccupationRatingFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<int>("OccupationTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OccupationRatingFactor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Factor = 1.0m,
                            OccupationTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Factor = 1.25m,
                            OccupationTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Factor = 1.50m,
                            OccupationTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Factor = 1.75m,
                            OccupationTypeId = 4
                        });
                });

            modelBuilder.Entity("PremiumCalculator.Web.API.Models.OccupationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("OccupationType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Professional"
                        },
                        new
                        {
                            Id = 2,
                            Name = "White Collar"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Light Manual"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Heavy Manual"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
